name: System roots

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    branches:
        - '**'
  push:
    branches:
        - '**'

permissions: write-all

jobs:
  cross-build:
    name: 'Cross build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          'aarch64-unknown-linux-musl',
          'armv6-unknown-linux-musleabihf',
          'armv7-unknown-linux-musleabihf',
          'i386-unknown-linux-musl',
          'x86_64-unknown-linux-musl'
        ]
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Generate system roots
      run: |
        declare -r RAIDEN_TAG='gcc-15'
        declare -r RAIDEN_TARBALL='/tmp/toolchain.tar.xz'
        declare -r RAIDEN_URL="https://github.com/AmanoTeam/musl-gcc-cross/releases/download/${RAIDEN_TAG}/x86_64-unknown-linux-gnu.tar.xz"
        
        curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --location --url "${RAIDEN_URL}" --output "${RAIDEN_TARBALL}"
        tar --directory="$(dirname "${RAIDEN_TARBALL}")" --extract --file="${RAIDEN_TARBALL}"
        
        unlink "${RAIDEN_TARBALL}"
        
        export RAIDEN_HOME='/tmp/raiden'
        export PATH="${RAIDEN_HOME}/bin:${PATH}"
        
        export CMAKE_TOOLCHAIN_FILE="${RAIDEN_HOME}/usr/local/share/mingw/cmake/${{ matrix.target }}.cmake"
        
        source "${RAIDEN_HOME}/build/autotools/${{ matrix.target }}.sh"
        
        bash './sysroot.sh'
    - name: Create release
      uses: softprops/action-gh-release@master
      with:
        tag_name: sysroot
        name: System roots
        files: /tmp/*.tar.xz*
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        body: "* Initial release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update timestamp
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        git branch timestamp
        git checkout timestamp
        
        date > timestamp
        git add timestamp
        git commit -m "Update timestamp"
        
        git push -f origin timestamp
